# Generated by Django 4.1.3 on 2022-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myfrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DOB', models.DateField(max_length=8)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
            ],
        ),
    ]
